apiVersion: v2
description: Artifact Attestations Policy Controller Helm Chart
home: https://github.com/github/policy-controller

sources:
  - https://github.com/github/policy-controller

type: application

name: policy-controller
version: "v0.12.0-github10"
appVersion: "v0.12.0-github10"

maintainers:
  - name: codysoyland
  - name: malancas
