apiVersion: v2
description: Artifact Attestations Policy Controller Helm Chart
home: https://github.com/github/policy-controller

sources:
  - https://github.com/github/policy-controller

type: application

name: policy-controller
version: "v0.10.0-github7"
appVersion: "v0.10.0-github7"

maintainers:
  - name: codysoyland
  - name: malancas
