apiVersion: v2
description: GitHub policy for the Artifact Attestations Policy Controller
home: https://github.com/github/policy-controller

sources:
  - https://github.com/github/policy-controller

type: application

name: trust-policies
version: "v0.6.0"
appVersion: "v0.6.0"

maintainers:
  - name: codysoyland
  - name: malancas
